language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
install:
  - "pip install -r requirements.txt"
  - "pip install coverage flake8"
  - "python setup.py install"
script: "nosetests -s"
notifications:
  email: false
